# Generated by Django 3.2.7 on 2021-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_image', models.ImageField(upload_to='img/')),
                ('f_content', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_image', models.ImageField(upload_to='img/')),
                ('g_title', models.CharField(max_length=20)),
                ('g_content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_image', models.ImageField(upload_to='img/')),
                ('m_title', models.CharField(max_length=20)),
                ('m_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_image_icon', models.ImageField(upload_to='img/')),
                ('s_image', models.ImageField(upload_to='img/')),
                ('s_title', models.CharField(max_length=20)),
                ('s_content', models.TextField(max_length=200)),
            ],
        ),
    ]
