# Generated by Django 3.2.7 on 2021-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal_hotel', '0002_auto_20210916_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_image', models.ImageField(upload_to='img/')),
                ('f_name', models.TextField(max_length=10)),
                ('f_content', models.TextField(max_length=550)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedbacks',
        ),
    ]
