# Generated by Django 3.2.7 on 2021-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal_hotel', '0003_auto_20210916_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='f_name',
            field=models.CharField(max_length=10),
        ),
    ]
